name: build-x-wrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata
          sudo apt -y autoremove --purge
          sudo apt clean

      - name: Clone source code
        run: git clone --depth 1 --branch master https://github.com/bimizx/x-wrt.git

      - name: Update feeds
        run: cd x-wrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd x-wrt && ./scripts/feeds install -a

      - name: Building
        run: |
          cp *.sh x-wrt/
          cp release.tag x-wrt/
          cd x-wrt
          echo -e "$(nproc) thread build."
          TARGET=mediatek-filogic sh build.sh $(nproc)

      - name: Upload make.log if failure
        uses: actions/upload-artifact@main
        if: failure()
        with:
          name: build-failure-log
          path: x-wrt/make.log

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: x-wrt-master-n =mediatek-filogic
          path: x-wrt/rom/
